<?php echo $this->render($this->baseUrl.'/header.phtml'); ?>
		
		<script type="text/javascript">
			
			function init(){

			}
			
			YAHOO.util.Event.onDOMReady(init);
		</script> 
		
	</head>
	
	<?php echo $this->render($this->baseUrl.'/banner.phtml'); ?>
 
				<div id="about" class="yui-g">
					
					<h3>About Meal Loop</h3>
					
					<p>
					Plain and simple, Meal Loop helps plan your meals.  By storing all your recipes 
					with Meal Loop, you can save time and get more organized by having Meal Loop create a meal plan especially for you.  
					Whether you like your meals chosen completely by random, or if you like to eat 
					chicken on Wednesday, Meal Loop allows you to customize your plan however you see fit.  Meal Loop also provides you with 
					a shopping list that includes a consolidated listing of ingredients you need for the upcoming week.  The best part about Meal Loop
					is that it is completely free!  All you need to get started is a valid email address.  We also promise not to 
					send you any unwanted mail or give your address away for our personal gain.
					</p>
					
					<div>
					Questions?  Comments?  Suggestions?  
					</div>
					<div>
					Contact: <a href="mailto:admin@mealloop.com">admin@mealloop.com</a>
					</div>

				</div>
		    
	<?php echo $this->render($this->baseUrl.'/footer.phtml'); ?>