		    </div> 
		   	<div id="footer">

				<div id="footerLinks">
					<a href="<?php echo $this->baseUrl ?>/about">About</a>&nbsp;
					<a href="<?php echo $this->baseUrl ?>/help">Help</a>&nbsp; 
					<a href="mailto:admin@mealloop.com">Contact</a>&nbsp;
				</div>
				<div>&copy; 2007 - <?php echo date('Y')?> &nbsp; <a	href="http://krehnbrink.com/2008/03/06/official-launch-meal-loop/">Sam Krehnbrink</a></div>
				
		</div> 
	</body> 
</html>