
<form action="<?php echo $this->baseUrl.'/'.$this->action; ?>" method="post">

<div class="registerRow">
	<label for="emailTF"><h4>*Email Address:</h4></label>
	<input name="emailTF" class="textfield" type="text" value="<?php if($this->user_data != null) echo $this->escape($this->user_data['email']);?>"/>
</div>
<div class="registerRow">
	<label for="email2TF"><h4>*Confirm Email:</h4></label>
	<input name="email2TF" class="textfield" type="text" value="<?php if($this->user_data != null) echo $this->escape($this->user_data['email2']);?>"/>
</div>

<div class="registerRow">
	<label for="passTF"><h4>*Password:</h4></label>
	<input name="passTF" class="textfield" type="password" value="<?php if($this->user_data != null) echo $this->escape($this->user_data['pass']);?>"/>
</div>
<div class="registerRow">
	<label for="pass2TF"><h4>*Confirm Password:</h4></label>
	<input name="pass2TF" class="textfield" type="password" value="<?php if($this->user_data != null) echo $this->escape($this->user_data['pass2']);?>"/>
</div>

<div class="registerRow">
	<label for="nameTF"><h4>Name:</h4></label>
	<input name="nameTF" class="textfield" type="text" value="<?php if($this->user_data != null) echo $this->escape($this->user_data['name']);?>"/>
</div>
<div class="registerRow">
	<label for="websiteTF"><h4>Website:</h4></label>
	<input name="websiteTF" class="textfield" type="text" value="<?php if($this->user_data != null) echo $this->escape($this->user_data['url']);?>"/>
</div>
<div id="registerButtons">
	<input id="submitBTN" type="submit" value="<?php echo $this->escape($this->buttonText); ?>" />
	<a class="buttonlink" href="<?php echo $this->baseUrl; ?>"><input id="cancelBTN" type="button" value="Cancel" /></a>
</div>
</form>